apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-case-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-case
  template:
    metadata:
      labels:
        app: devops-case
    spec:
      containers:
      - name: devops-case
        image: hefekaraca/devops-case:latest   
        ports:
        - containerPort: 5003
        livenessProbe:
          httpGet:
            path: /health
            port: 5003
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: devops-case-service
spec:
  type: NodePort   
  selector:
    app: devops-case
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5003
    nodePort: 30007   
